### ISSUE TITLE
On first install, on selecting to install all plugins nothing is displayed

### ISSUE THREAD

**Issue by logotie** [xgi/houdoku#6] opened 2019-06-25 18:32 UTC
Hey dude, 

Thank you so much for adding comments in the code haha!  :)

I am going to add some issues and once I get to grips with the code, I will probably just self assign them.

Issue:
When the jar has been downloaded and ran for the first time, on installing all the plugins nothing happens.
---
Windows 10, Java Version 8 Update 201
1.  Install and open the app as a new install.
2.  Click on File>Settings>Plugin>Install/Update plugins.
3.  Select all of them and click ok.
4. **Observe** nothing happens
5.  On proceeding to click 'Install/Update plugins' again the following error is displayed:

![image](https://user-images.githubusercontent.com/26583547/60123666-eb8c6c00-977f-11e9-8199-e439c3ccc96d.png)

**Comment by xgi** [comment] 2019-06-26 02:06
I can confirm the issue with plugins not appearing after the first install. It seems like the client is failing to load them for some reason, even though they successfully download. I wasn't able to personally reproduce the error you got, though, and it seems strange since it loads properly the first time.

The first part at least should probably be addressed before the next release, but I'll leave it for now in case you want to look into it (I don't have a timeline or anything).

Thanks!

**Comment by xgi** [comment] 2019-06-28 23:46
This was fixed in 342371d10d91a8a804bacd41398085fdce4e41e2. The issue was that the plugin loader depended on the `plugins` directory existing when the client was loaded, which is not the case until plugins have been installed.

**Closed by xgi** 2019-06-28 23:46 UTC
