### ISSUE TITLE
Confusing Directory Naming

### ISSUE THREAD

**Issue by maisans-maid** [xgi/houdoku#35] opened 2021-05-30 16:52 UTC
You mentioned that that we must follow your recommended directory tree. But doing this limits our freedom to name chapter via their intended titles

1. With a directory like -> `Documents\Hatsukoi Zombie\Hatsukoi Zombie v1\Hatsukoi Zombie v1 c1` - The chapter title will be `Hatsukoi v1 c1`. If i want to make my own chapter name, like: `Documents\Hatsukoi Zombie\Hatsukoi Zombie v1\The Beginning`, the chapter will be `The Beginning` but the context of the volume and chapter is lost (where a chapter being lost in context is acceptable, the volume being lost seems ridiculous, as it is inside the directory with v1 in it, the app should be able to detect the volume through it)

2. If the root folder name is the manga title, why does the app detects the title from the very first chapter folder? I.e. With a directory like ->  `\Hatsukoi Zombie\Hatsukoi Zombie v1\Hatsukoi Zombie v1 c1` , the Manga Title will be Hatsukoi Zombie, but if I make it  `\Hatsukoi Zombie\Hatsukoi Zombie v1\[v1c1] The Beginning`, the Manga Title for the entry will be `[`. It should be `Hatsukoi Zombie` since it is the root directory, but it chooses to select the name from the subdirectories instead.

3. Adding the Scanlation Source formatting makes no difference, it does not reflect on the metadata whatsoever. It just adds into the chapter title, which is still in the same format. If it was indeed a feature, it should have been like, another column for the scanlation source if the user provided it in the folder name.

Overall, it just confuses me. I wasted 3+hours just to configure a single volume single chapter into my liking.

**Comment by xgi** [comment] 2021-05-30 18:30
Sorry for the frustration.

1. I think the wiki is actually incorrect with saying "Manga Title" for all of the subdirectories. The manga title is only actually taken from the root directory name. So you can include the custom chapter title in the chapter directory's name, like `[Group] My Chapter Name v1 c1` or `[Group] v1 c1 My Chapter Name` or `My Chapter Name v1 c1 [Group]`. I'll update the wiki to reflect this.
2. For your example with `\Hatsukoi Zombie\Hatsukoi Zombie v1\[v1c1] The Beginning` detecting the manga title incorrectly: did this actually happen, or are you just interpreting what the wiki says will happen? The chapter parser shouldn't have any effect on the manga title, which is actually taken from the root directory as you expected it should.
3. The group name is saved in the chapter metadata. If you go to read a chapter it should state the group name on the left sidebar. I've also updated (for a future release) the chapter table display so it includes a column for this group name that you can filter from. However you're right, the actual "chapter title", as it's shown in the table, is just the full directory name. This was sort-of just a failsafe in case the other metadata wasn't extracted properly, but I can look into excluding the group/volumenum/chapternum from the title to make it cleaner.

**Comment by maisans-maid** [comment] 2021-05-31 11:52
> Sorry for the frustration.
> 
> 1. I think the wiki is actually incorrect with saying "Manga Title" for all of the subdirectories. The manga title is only actually taken from the root directory name. So you can include the custom chapter title in the chapter directory's name, like `[Group] My Chapter Name v1 c1` or `[Group] v1 c1 My Chapter Name` or `My Chapter Name v1 c1 [Group]`. I'll update the wiki to reflect this.
> 2. For your example with `\Hatsukoi Zombie\Hatsukoi Zombie v1\[v1c1] The Beginning` detecting the manga title incorrectly: did this actually happen, or are you just interpreting what the wiki says will happen? The chapter parser shouldn't have any effect on the manga title, which is actually taken from the root directory as you expected it should.
> 3. The group name is saved in the chapter metadata. If you go to read a chapter it should state the group name on the left sidebar. I've also updated (for a future release) the chapter table display so it includes a column for this group name that you can filter from. However you're right, the actual "chapter title", as it's shown in the table, is just the full directory name. This was sort-of just a failsafe in case the other metadata wasn't extracted properly, but I can look into excluding the group/volumenum/chapternum from the title to make it cleaner.

It did actually happen. Can you replicate that issue in your end? I removed and readded the series 3 times with that configuration and it always happens.

**Comment by maisans-maid** [comment] 2021-05-31 11:55
also, i did something like that. `My Chapter Name v1 c1`, but the manga title becomes `My Chapter Name`. Of course, this happens when adding the manga to the library.

**Comment by maisans-maid** [comment] 2021-05-31 12:43
Here's a screenshot of the directory (with the content inside the chapter folder)

![image](https://user-images.githubusercontent.com/56829176/120194672-7c173500-c250-11eb-95fe-c41f3f166448.png)

As you can see `^`, The one marked in green should be the root directory, but it takes the chapter name as the manga title (yellow) instead. Below is a record as a proof, using that same directory

![Animation](https://user-images.githubusercontent.com/56829176/120194900-c698b180-c250-11eb-8e74-a3e8c0a9327a.gif)

**Comment by maisans-maid** [comment] 2021-05-31 12:45
Also, what's the need of having the volume number in the name of the chapter directory, does this mean that we can just entirely omit the volume dir and just have the all the chapters inside the root directory with the volume number on their dirname instead?

**Comment by maisans-maid** [comment] 2021-05-31 12:52
>  However you're right, the actual "chapter title", as it's shown in the table, is just the full directory name. This was sort-of just a failsafe in case the other metadata wasn't extracted properly, but I can look into excluding the group/volumenum/chapternum from the title to make it cleaner.

I kinda just assumed that the volume number and chapter number get kinda parsed out since it is what is shown in your screenshot below (there is no v1 c1 or something in the chapter title, but the chapter title and volume number was kinda parsed out) 

![image](https://user-images.githubusercontent.com/56829176/120195666-a1587300-c251-11eb-82f4-d87365eea78b.png)

Also, where do i input the synopsis metadata? can you add the ability to just edit it initially? just like the genres and stuff? And also the banner for the manga? Im assuming its from anilist? Since i saw some traces of the app connecting to anilist when i checked the console.

**Comment by xgi** [comment] 2021-05-31 13:46
> It did actually happen. Can you replicate that issue in your end? I removed and readded the series 3 times with that configuration and it always happens.

Okay, I was just able to reproduce the chapter name becoming the manga title, but only when there's exactly one chapter folder. Thanks for the gif.

> Also, what's the need of having the volume number in the name of the chapter directory, does this mean that we can just entirely omit the volume dir and just have the all the chapters inside the root directory with the volume number on their dirname instead?

Yes, you don't need volume dirs. Their names aren't even parsed. I used them in the "recommended structure" on the wiki because most releases I've seen included them and I (ironically) wanted to make it easier. I'll make this an alternate example on the wiki.

> Also, where do i input the synopsis metadata? can you add the ability to just edit it initially? just like the genres and stuff? And also the banner for the manga? Im assuming its from anilist? Since i saw some traces of the app connecting to anilist when i checked the console.

Sure, I can add a description field to the modal. The reason the series in the screenshot had a description (and better chapter titles) is because it was added from a content source (Extensions tab on the left) which have their own parsers. Heads up though I've made some major changes with them since the last released version.

Yeah, the banners are from Anilist. I can look into letting them be customized, but that probably won't happen soon.

**Comment by maisans-maid** [comment] 2021-05-31 14:50
Oh, also, i had to add this. You said on your wiki that the chapters can have the decimal, but this doesn't get parsed actually. When i put 7.5 on chapter, it just being treated as chapter 7, messing up the order.
![image](https://user-images.githubusercontent.com/56829176/120210552-7a566d00-c262-11eb-9400-0394f0f8f477.png)

P.S. When will you drop the next release for the fixes?

**Comment by xgi** [comment] 2021-06-01 18:25
Next release will be in about 2 weeks.

**Closed** 2021-06-13 21:33 UTC
