### ISSUE TITLE
Library not updating and then the app freezing.

### ISSUE THREAD

**Issue by jojopops** [xgi/houdoku#163] opened 2022-07-09 16:35 UTC
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

v2.9.1

### Operating system

Windows 10

### Steps to reproduce

1. Start the app.
2. Wait for the app update and library update to commence.
3. App freezes when it starts to update the library.
4. Close the app.
5. Repeat steps 1-4.
6. -------
7. Go to add series window
8. Hover over "Extension:" tab. The app freezes
9. Repeat steps 7-8.

### Expected behavior

The expected behavior would be the app updates the library properly without freezing.

The add series window at the "Extension:" tab should allow us to add a new series without freezing.

### Actual behavior

When I turn on the app it checks for updates for the app just fine but when it starts to update the library it freezes and after some time it says something like, "An error occurred". It does this every time I start the app. This started happening after I updated to the latest version of the app. The extensions are updated to the newest version I checked and rechecked this, and also, deleted the extensions via the app menu and also manually and then reinstalled them but that didn't work. This same freezing bug occurs when I try to add a new series to my library. It doesn't even let me click the dropdown for the "Extension:" tab the app freezes when I hover my mouse over the tab.

**Comment by xgi** [comment] 2022-07-09 23:54
I'm not able to reproduce this -- can you upload your log files? From `%APPDATA%/Roaming/Houdoku/logs`

**Comment by jojopops** [comment] 2022-07-10 03:53
[main.log](https://github.com/xgi/houdoku/files/9078388/main.log)
[renderer.log](https://github.com/xgi/houdoku/files/9078389/renderer.log)

I tried to update the library again a few moments ago and it worked like normal so I don't know if the error did reoccur. I deleted and then reinstall the entire app so maybe that fixed the problem. 

The logs are from after the reinstall.

**Comment by xgi** [comment] 2022-07-14 18:58
This should be resolved with v2.9.2. Thanks!

**Closed by xgi** 2022-07-14 18:58 UTC
Labels: bug
