### ISSUE TITLE
Library gets scrambled after Update v2.9.0 on Startup

### ISSUE THREAD

**Issue by ScruffiX** [xgi/houdoku#153] opened 2022-06-25 19:44 UTC
### Acknowledgements

- [X] Ensure that Houdoku is up-to-date (check the About tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with an extension, open a ticket in the [extensions repo](https://github.com/xgi/houdoku-extensions/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

v2.9.0

### Operating system

Windows 10

### Steps to reproduce

1. Have your normal library
2. Restart Houdoku
3. Library Entries are scrambled

### Expected behavior

The library does not get scrambled upon startup.

### Actual behavior

When you startup Houdoku and all the entries get updated, some of them get mixed up. 
![image](https://user-images.githubusercontent.com/15036358/175788172-5c10498a-0dbd-4c90-9029-048b2ebc04d6.png)
In this Example, Hellper got the Title God of Highschool (as you can see it exists twice). Same with Berserk; it replaced another series.
It'll keep the correct chapters but the title, banner and description get replaced.
![image](https://user-images.githubusercontent.com/15036358/175788150-56b3b252-7a1d-4664-af77-8b9e3e55fb3d.png)
In some earlier cases, of which I do not have screenshots, even the chapters got copied to another entry in the library. This was fixed by uninstalling Houdoku, deleting the Roaming folder, reinstalling Houdoku and, re-adding all series manually (loaded Backup is still bricked).

### Log files

[main.log](https://github.com/xgi/houdoku/files/8985455/main.log)
[renderer.log](https://github.com/xgi/houdoku/files/8985456/renderer.log)

### Additional information (optional)

This problem only occured once Update v2.9.0 was installed.

**Comment by xgi** [comment] 2022-06-26 05:00
To clarify, does this scrambling/duplication continue to happen when you restart Houdoku?

If so, can you create a backup of your library (from the settings page) and upload that JSON file? I have a guess of the issue but I'd need to see the series data to verify and I'm not able to reproduce it myself.

**Comment by ScruffiX** [comment] 2022-06-26 08:02
So from what I could tell it is actually somewhat random. On some startups it's fine and nothing gets mixed up and on other startups it messes up the library. But it is definetly re-creatable by just restarting over and over (at least for me)

And here is the backup (in a zip coz github doesn't want json files)
[houdoku_series_backup_2022-06-26.zip](https://github.com/xgi/houdoku/files/8986204/houdoku_series_backup_2022-06-26.zip)

**Comment by BoreasAetheris** [comment] 2022-06-26 17:12
I have exactly the same issue. But i think it's getting worse.
In the beginning it didn't happen often but now i have to reload quite a few times before it's right.
Though it could also be random ofcourse
(btw nice series ur reading)

**Comment by Bernard0018** [comment] 2022-07-01 07:17
I also encounter this bug, I think this will happen if you turn on the "Refresh Library on Startup" in the setting. The only solution I can come up is to refresh all the series one by one. Hope this gets fix quickly.

**Comment by xgi** [comment] 2022-07-02 08:39
This has been fixed with fffdd518fe0a944897197855ad3e8c3655805cb9. It'll be included in an update in a few days. Thanks!

**Closed by xgi** 2022-07-02 08:39 UTC
Labels: bug
